# Generated by Django 4.0.3 on 2022-04-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activeStudent',
            fields=[
                ('A_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('S_Id', models.IntegerField()),
                ('sessionid', models.CharField(default='sadbfahfdsfhhKJHeehhOHugu', max_length=200)),
            ],
            options={
                'db_table': 'activeStudent',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('S_Id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('S_Name', models.CharField(default=False, max_length=100)),
                ('S_Email', models.CharField(default=False, max_length=100)),
                ('S_Mob', models.CharField(default=False, max_length=10)),
                ('S_Password', models.CharField(default=False, max_length=45)),
                ('S_Dept', models.CharField(default=False, max_length=45)),
                ('S_RegId', models.CharField(default=False, max_length=45)),
                ('S_Sec', models.CharField(default=False, max_length=45)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
