# Generated by Django 3.2.12 on 2022-04-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activeFaculty',
            fields=[
                ('A_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('F_Id', models.IntegerField()),
                ('sessionid', models.CharField(default='sadbfahfdsfhhKJHeehhOHugu', max_length=200)),
            ],
            options={
                'db_table': 'activefaculty',
            },
        ),
        migrations.CreateModel(
            name='dummy',
            fields=[
                ('id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('key_t', models.CharField(default=False, max_length=10)),
                ('value_t', models.CharField(default=False, max_length=100)),
                ('dob', models.CharField(default=False, max_length=100)),
            ],
            options={
                'db_table': 'dummmy',
            },
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('F_Id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('F_Name', models.CharField(default=False, max_length=100)),
                ('F_Email', models.CharField(default=False, max_length=100)),
                ('F_Mob', models.CharField(default=False, max_length=10)),
                ('F_Password', models.CharField(default=False, max_length=45)),
                ('F_Dept', models.CharField(default=False, max_length=45)),
                ('F_RegId', models.CharField(default=False, max_length=45)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='publications',
            fields=[
                ('P_Id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('P_Title', models.CharField(default=False, max_length=500)),
                ('P_Joural_Name', models.CharField(default=False, max_length=500)),
                ('P_Indexing', models.CharField(default=False, max_length=45)),
                ('P_IF_State', models.CharField(default=False, max_length=100)),
                ('P_IF_Value', models.CharField(default=False, max_length=20)),
                ('P_IF_Source', models.CharField(default=False, max_length=20)),
                ('P_DOP', models.CharField(default=False, max_length=20)),
                ('P_DOI', models.CharField(default=False, max_length=250)),
                ('P_Page_Nos', models.CharField(default=False, max_length=45)),
                ('P_ISSN', models.CharField(default=False, max_length=45)),
                ('P_Volume', models.CharField(default=False, max_length=20)),
                ('P_Issue', models.CharField(default=False, max_length=20)),
                ('P_Journal_Source', models.CharField(default=False, max_length=500)),
                ('P_Paper_Source', models.FileField(default=False, max_length=500, upload_to='')),
            ],
            options={
                'db_table': 'publications',
            },
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('technologies', models.CharField(max_length=500)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('display_picture', models.FileField(upload_to='')),
            ],
        ),
    ]
