# Generated by Django 4.0.4 on 2022-04-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20220408_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='pfconnect',
            fields=[
                ('PF_Id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('P_Id', models.IntegerField(default=False)),
                ('F_Id', models.IntegerField(default=False)),
                ('F_Pos', models.IntegerField(default=False)),
            ],
            options={
                'db_table': 'pfconnect',
            },
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_DOI',
            field=models.CharField(default='', max_length=250, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_IF_Source',
            field=models.CharField(default='', max_length=20, verbose_name='Impact Facotr Source'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_IF_State',
            field=models.CharField(default='', max_length=100, verbose_name='Impact Factor State'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_IF_Value',
            field=models.CharField(default='', max_length=20, verbose_name='Impact Factor Value'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_ISSN',
            field=models.CharField(default='', max_length=45, verbose_name='ISSN'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_Id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Publication ID'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_Indexing',
            field=models.CharField(default='', max_length=45, verbose_name='Indexing'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_Issue',
            field=models.CharField(default='', max_length=20, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_Joural_Name',
            field=models.CharField(default='', max_length=500, verbose_name='Journal Name'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_Journal_Source',
            field=models.CharField(default='', max_length=500, verbose_name='Journal Source'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_Page_Nos',
            field=models.CharField(default='', max_length=45, verbose_name='Number of Pages'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_Paper_Source',
            field=models.FileField(default='', max_length=500, upload_to='', verbose_name='Paper Source'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_Title',
            field=models.CharField(max_length=500, verbose_name='Publication Title'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='P_Volume',
            field=models.CharField(default='', max_length=20, verbose_name='Volume'),
        ),
    ]
