# Generated by Django 4.0.4 on 2022-04-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_pfconnect_f_id_alter_pfconnect_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfconnect',
            name='F_Id',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='pfconnect',
            name='P_Id',
            field=models.IntegerField(default=False),
        ),
    ]
